PSPSDK: debug/gdb-kernellib.c File Reference
gdb-kernellib.c File Reference
#include <pspkernel.h>
#include <pspdebug.h>
Functions
void putDebugChar (char ch)
char getDebugChar (void)
void sceKernelDcacheWBinvAll (void)
void sceKernelIcacheClearAll (void)
void _gdbSupportLibFlushCaches (void)
int _gdbSupportLibReadByte (unsigned char *address, unsigned char *dest)
int _gdbSupportLibWriteByte (char val, unsigned char *dest)
int _gdbSupportLibInit (void)
Function Documentation
_gdbSupportLibFlushCaches()
void _gdbSupportLibFlushCaches (void)
References pspKernelSetKernelPC, sceKernelDcacheWBinvAll(), and sceKernelIcacheClearAll().
_gdbSupportLibInit()
int _gdbSupportLibInit (void)
_gdbSupportLibReadByte()
int _gdbSupportLibReadByte (unsigned char * address, unsigned char * dest)
_gdbSupportLibWriteByte()
int _gdbSupportLibWriteByte (char val, unsigned char * dest)
getDebugChar()
char getDebugChar (void)
References pspDebugSioGetchar().
putDebugChar()
void putDebugChar (char ch)
References pspDebugSioPutchar().
sceKernelDcacheWBinvAll()
void sceKernelDcacheWBinvAll (void)
Referenced by _gdbSupportLibFlushCaches().
sceKernelIcacheClearAll()
void sceKernelIcacheClearAll (void)
Referenced by _gdbSupportLibFlushCaches(), and pspSdkFixupImports().